python_library(
    # name defaults to the name of this directory, i.e., `util`.
    # sources defaults to ['*.py', '!*_test.py', '!test_*.py', '!conftest.py'].
    dependencies = [
        "3rdparty/python:setuptools",
    ]
)
